# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "legendary_monsters:overgrown_colossus",
    "alexsmobs:snow_leopard",
    "companions:cloak",
    "zombie_island:walker_3",
    "zombie_island:walker_4",
    "zombie_island:walker_1",
    "alexsmobs:seal",
    "zombie_island:walker_2",
    "zombie_island:eat_courier",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "pomkotsmechs:pmv01b",
    "minecraft:trader_llama",
    "apocalypsenow:soldiers_02",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "zombie_island:firefighter_walker",
    "minecraft:llama",
    "alexsmobs:maned_wolf",
    "zombie_extreme:goon",
    "extinction:infected_police",
    "alexsmobs:skreecher",
    "minecraft:tadpole",
    "minecraft:dolphin",
    "apocalypsenow:rat",
    "zombie_extreme:devestated",
    "pomkotsmechs:pmb06",
    "pomkotsmechs:pmb05",
    "alexsmobs:gelada_monkey",
    "apocalypsenow:hunter",
    "pomkotsmechs:pmb04",
    "pomkotsmechs:pmb03",
    "pomkotsmechs:pmb02",
    "pomkotsmechs:pmb01",
    "companions:cornelius",
    "zombie_extreme:infected_military",
    "alexsmobs:hammerhead_shark",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "alexsmobs:grizzly_bear",
    "legendary_monsters:shulker_mimic",
    "alexsmobs:murmur_head",
    "legendary_monsters:haunted_knight",
    "zombie_island:grenadier_walker",
    "extinction:runner",
    "zombie_extreme:divided",
    "minecraft:bee",
    "alexsmobs:devils_hole_pupfish",
    "sona:sound_decoy",
    "minecraft:illusioner",
    "zombiesmore:explosive_zombie",
    "companions:ember_pole",
    "minecraft:mooshroom",
    "legendary_monsters:stratling",
    "alexsmobs:bison",
    "minecraft:drowned",
    "minecraft:axolotl",
    "zombie_extreme:faceless",
    "legendary_monsters:ambusher",
    "zombie_extreme:revived",
    "alexsmobs:gorilla",
    "pomkotsmechs:pmt04",
    "pomkotsmechs:pmt03",
    "pomkotsmechs:pmt02",
    "pomkotsmechs:pmt01",
    "mythicmounts:nudibranch",
    "zombie_island:insect_swarm_walker",
    "alexsmobs:tusklin",
    "pomkotsmechs:playerdummy",
    "companions:croissant_dragon",
    "alexsmobs:cosmic_cod",
    "apocalypsenow:horde_2",
    "apocalypsenow:horde_3",
    "apocalypsenow:horde_4",
    "alexsmobs:underminer",
    "apocalypsenow:horde_5",
    "zombie_extreme:boomer",
    "mythicmounts:direwolf",
    "apocalypsenow:horde_1",
    "extinction:soldier_clicker",
    "minecraft:wandering_trader",
    "zombiesmore:boomer_zombie",
    "extinction:patient_zero",
    "alexsmobs:kangaroo",
    "legendary_monsters:skeloraptor",
    "zombiesmore:cursed_head",
    "legendary_monsters:bomber",
    "companions:shade_maw",
    "extinction:patient_zero_i",
    "mythicmounts:colelytra",
    "alexsmobs:hummingbird",
    "pomkotsmechs:pms09",
    "pomkotsmechs:pms08",
    "pomkotsmechs:pms07",
    "pomkotsmechs:pms06",
    "extinction:infected_hazmat",
    "pomkotsmechs:pms05",
    "pomkotsmechs:pms04",
    "pomkotsmechs:pms03",
    "hordes:drowned_player",
    "pomkotsmechs:pms02",
    "zombiesmore:tank_zombie",
    "pomkotsmechs:pms01",
    "alexsmobs:crow",
    "dyairdrop:plane",
    "apocalypsenow:soldiers",
    "alexsmobs:guster",
    "zombie_island:shambler",
    "minecraft:pufferfish",
    "pomkotsmechs:pmv03p",
    "minecraft:fox",
    "mythicmounts:firebird",
    "alexsmobs:warped_toad",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "alexsmobs:emu",
    "clanginghowl:extraterrestrial_reaper",
    "alexsmobs:cockroach",
    "apocalypsenow:looter_3",
    "companions:golden_allay",
    "pomkotsmechs:pmv03",
    "apocalypsenow:looter_4",
    "pomkotsmechs:pmv02",
    "extinction:mercenary",
    "apocalypsenow:looter_5",
    "pomkotsmechs:pmv01",
    "zombie_island:hazmat_walker",
    "alexsmobs:flutter",
    "apocalypsenow:looter_1",
    "minecraft:hoglin",
    "apocalypsenow:looter_2",
    "legendary_monsters:warped_fungussus",
    "mythicmounts:netherbat",
    "alexsmobs:capuchin_monkey",
    "hordes:husk_player",
    "apocalypsenow:walker_3",
    "minecraft:polar_bear",
    "apocalypsenow:walker_2",
    "companions:nether_bullfrog",
    "apocalypsenow:walker_5",
    "apocalypsenow:walker_4",
    "minecraft:zombified_piglin",
    "apocalypsenow:walker_1",
    "companions:soul_mage",
    "minecraft:turtle",
    "apocalypsenow:walker_7",
    "minecraft:sheep",
    "apocalypsenow:walker_6",
    "mythicmounts:griffon",
    "apocalypsenow:walker_9",
    "apocalypsenow:walker_8",
    "zombie_island:walker",
    "alexsmobs:rattlesnake",
    "companions:sacred_pontiff",
    "zombie_extreme:assasin_black_ops",
    "legendary_monsters:frostbitten_golem",
    "alexsmobs:bone_serpent_part",
    "extinction:goon",
    "alexsmobs:raccoon",
    "companions:shade_sword",
    "minecraft:ravager",
    "alexsmobs:bone_serpent",
    "zombie_extreme:runner",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "dyairdrop:weaponairdrop",
    "mythicmounts:courierbird",
    "alexsmobs:straddler",
    "mythicmounts:archelon",
    "alexsmobs:sea_bear",
    "extinction:boomer",
    "mythicmounts:moth",
    "alexsmobs:mudskipper",
    "alexsmobs:sugar_glider",
    "zombie_island:riot_gear_walker",
    "alexsmobs:crimson_mosquito",
    "pomkotsmechs:pmb01mk2",
    "alexsmobs:orca",
    "mythicmounts:nightmare",
    "legendary_monsters:cloud_golem",
    "extinction:infected_mutated",
    "alexsmobs:jerboa",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "legendary_monsters:knights_armor",
    "mythicmounts:acencia",
    "alexsmobs:comb_jelly",
    "apocalypsenow:runner_39",
    "apocalypsenow:runner_38",
    "apocalypsenow:runner_37",
    "zombie_island:caustic_x_walker",
    "zombie_island:runner",
    "apocalypsenow:runner_36",
    "legendary_monsters:withered_abomination",
    "apocalypsenow:runner_35",
    "apocalypsenow:runner_34",
    "apocalypsenow:crawler_3",
    "companions:ender_frog",
    "apocalypsenow:survivor_10",
    "apocalypsenow:crawler_2",
    "apocalypsenow:crawler_4",
    "apocalypsenow:crawler_1",
    "apocalypsenow:cockroach",
    "alexsmobs:skunk",
    "extinction:stalker_ii",
    "alexsmobs:enderiophage",
    "apocalypsenow:runner_49",
    "apocalypsenow:runner_48",
    "zombie_extreme:fetus",
    "rpg_companions_tiny_dragons:tiny_dragon_03",
    "alexsmobs:sunbird",
    "rpg_companions_tiny_dragons:tiny_dragon_02",
    "rpg_companions_tiny_dragons:tiny_dragon_01",
    "apocalypsenow:runner_43",
    "rpg_companions_tiny_dragons:tiny_dragon_07",
    "apocalypsenow:runner_42",
    "rpg_companions_tiny_dragons:tiny_dragon_06",
    "apocalypsenow:runner_41",
    "rpg_companions_tiny_dragons:tiny_dragon_05",
    "alexsmobs:tasmanian_devil",
    "apocalypsenow:runner_40",
    "rpg_companions_tiny_dragons:tiny_dragon_04",
    "apocalypsenow:runner_47",
    "apocalypsenow:runner_46",
    "apocalypsenow:runner_45",
    "zombie_extreme:zero_patient",
    "rpg_companions_tiny_dragons:tiny_dragon_09",
    "apocalypsenow:runner_44",
    "rpg_companions_tiny_dragons:tiny_dragon_08",
    "minecraft:cat",
    "alexsmobs:stradpole",
    "apocalypsenow:runner_50",
    "minecraft:tropical_fish",
    "rpg_companions_tiny_dragons:tiny_dragon_10",
    "zombie_extreme:chainsaw",
    "apocalypsenow:runner_54",
    "apocalypsenow:runner_53",
    "apocalypsenow:runner_52",
    "minecraft:panda",
    "minecraft:zombie_villager",
    "apocalypsenow:runner_51",
    "apocalypsenow:runner_57",
    "zombie_extreme:crawler",
    "apocalypsenow:runner_56",
    "apocalypsenow:runner_55",
    "dyairdrop:medicalairdrop",
    "alexsmobs:froststalker",
    "zombie_extreme:demolisher",
    "minecraft:giant",
    "dyairdrop:transportplane",
    "alexsmobs:lobster",
    "alexsmobs:seagull",
    "zombie_extreme:infected",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "companions:puppet_glove",
    "alexsmobs:farseer",
    "legendary_monsters:mossy_golem",
    "alexsmobs:warped_mosco",
    "zombie_extreme:parasite",
    "hordes:zombie_player",
    "zombie_extreme:infected_juggernaut",
    "clanginghowl:heart_of_decay",
    "minecraft:husk",
    "extinction:infected_riot_gear",
    "legendary_monsters:haunted_guard",
    "alexsmobs:komodo_dragon",
    "minecraft:donkey",
    "minecraft:piglin_brute",
    "extinction:traveler",
    "alexsmobs:crocodile",
    "apocalypsenow:military_medic",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "alexsmobs:frilled_shark",
    "alexsmobs:bald_eagle",
    "extinction:soldier",
    "alexsmobs:blobfish",
    "zombie_island:shocking_walker",
    "alexsmobs:mimicube",
    "zombie_extreme:infected_police",
    "alexsmobs:void_worm",
    "zombiesmore:boomer_charged",
    "minecraft:parrot",
    "dyairdrop:smallairdrop",
    "zombie_extreme:inflated",
    "companions:broken_dinamo",
    "alexsmobs:centipede_head",
    "companions:puppet",
    "zombie_island:incendiary_walker",
    "minecraft:frog",
    "companions:antlion",
    "legendary_monsters:guard",
    "mythicmounts:ridinglizard",
    "zombie_extreme:clicker",
    "alexsmobs:banana_slug",
    "alexsmobs:mimic_octopus",
    "alexsmobs:bunfungus",
    "alexsmobs:void_worm_part",
    "zombie_island:runner_2",
    "zombie_island:runner_1",
    "clanginghowl:flesh_maiden",
    "zombie_extreme:explosive_infected",
    "minecraft:mule",
    "zombie_island:shambler_4",
    "companions:minion",
    "zombie_island:shambler_3",
    "minecraft:vindicator",
    "mythicmounts:dragon",
    "zombie_island:burning_walker",
    "zombie_island:runner_4",
    "alexsmobs:flying_fish",
    "zombie_island:runner_3",
    "minecraft:evoker",
    "companions:firework_toad",
    "zombie_island:shambler_2",
    "zombie_island:shambler_1",
    "zombie_extreme:infected_hazmat",
    "alexsmobs:tarantula_hawk",
    "companions:hostile_imp",
    "alexsmobs:cachalot_whale",
    "legendary_monsters:spiky_bug",
    "zombie_extreme:ram",
    "companions:living_candle",
    "mythicmounts:geckotoalizard",
    "apocalypsenow:walker_29",
    "apocalypsenow:walker_28",
    "apocalypsenow:walker_27",
    "companions:illager_golem",
    "apocalypsenow:walker_26",
    "apocalypsenow:walker_25",
    "apocalypsenow:walker_24",
    "apocalypsenow:walker_23",
    "apocalypsenow:walker_22",
    "apocalypsenow:walker_21",
    "apocalypsenow:walker_20",
    "alexsmobs:terrapin",
    "zombiesmore:cursed_zombie",
    "alexsmobs:anaconda",
    "minecraft:pig",
    "legendary_monsters:hovering_hurricane",
    "alexsmobs:alligator_snapping_turtle",
    "extinction:infected_bear",
    "legendary_monsters:dune_sentinel",
    "apocalypsenow:walker_33",
    "apocalypsenow:walker_32",
    "apocalypsenow:walker_31",
    "apocalypsenow:walker_30",
    "minecraft:goat",
    "minecraft:cod",
    "alexsmobs:mantis_shrimp",
    "zombie_extreme:rat_king",
    "alexsmobs:platypus",
    "legendary_monsters:posessed_paladin",
    "extinction:hunter",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "alexsmobs:soul_vulture",
    "gravestone:player_ghost",
    "apocalypsenow:survivor_5",
    "apocalypsenow:survivor_4",
    "apocalypsenow:survivor_3",
    "apocalypsenow:survivor_2",
    "alexsmobs:blue_jay",
    "apocalypsenow:survivor_1",
    "alexsmobs:toucan",
    "minecraft:salmon",
    "apocalypsenow:walker_19",
    "apocalypsenow:walker_18",
    "dyairdrop:airdrop",
    "apocalypsenow:walker_17",
    "apocalypsenow:survivor_9",
    "apocalypsenow:walker_16",
    "apocalypsenow:survivor_8",
    "apocalypsenow:walker_15",
    "apocalypsenow:survivor_7",
    "apocalypsenow:walker_14",
    "extinction:parasite",
    "apocalypsenow:survivor_6",
    "apocalypsenow:walker_13",
    "apocalypsenow:walker_12",
    "apocalypsenow:walker_11",
    "alexsmobs:anteater",
    "apocalypsenow:walker_10",
    "companions:hostile_puppet_glove",
    "alexsmobs:rain_frog",
    "extinction:stalker",
    "minecraft:rabbit",
    "minecraft:pillager",
    "alexsmobs:murmur",
    "minecraft:zoglin",
    "legendary_monsters:chorusling",
    "alexsmobs:leafcutter_ant",
    "legendary_monsters:ancient_guardian",
    "zombie_extreme:night_hunter",
    "alexsmobs:mungus",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "alexsmobs:catfish",
    "extinction:fallen_survivor",
    "legendary_monsters:skeletosaurus",
    "minecraft:piglin",
    "legendary_monsters:lava_eater",
    "alexsmobs:skelewag",
    "extinction:infected_soldier",
    "alexsmobs:elephant",
    "apocalypsenow:military_02",
    "companions:wild_antlion",
    "apocalypsenow:military_01",
    "alexsmobs:gazelle",
    "pomkotsmechs:pmvc01",
    "minecraft:sniffer",
    "companions:dinamo",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "apocalypsenow:cannibal",
    "zombie_extreme:military",
    "zombiesmore:crawler",
    "companions:bubble_frog",
    "companions:mankh",
    "legendary_monsters:endersent",
    "companions:teddy",
    "minecraft:ocelot",
    "minecraft:wolf",
    "extinction:runner_ii"
]
