"Use new arrow turret model" = true
"Show turret and drone integrity" = true
"Enable drone flying sound" = false
"Use new bullet turret model" = true
"Use new cobble turret model" = true
"Use new fireball turret model" = true
"Use new brick turret model" = true

