
#Whisper Config
#Multipliers that affect the detection range and movement speed when the player is whispering.
[whisper_configs]
	#Range: 0.0 ~ 1.0
	whisper_range_multiplier = 0.5
	#Range: 0.0 ~ 1.0
	whisper_speed_multiplier = 0.8

#Mob Speed Boost Config
#Enable or disable the mob speed boost when targeting speaking players
[mob_speed_boost]
	mob_speed_boost_enabled = true

#Misc Config
#Multipliers that affect the detection range of voices in specific situations.
[misc_config]
	#Range: 0.0 ~ 1.0
	thunder_range_multiplier = 0.65
	#Range: 0.0 ~ 1.0
	sneaking_range_multiplier = 0.5

#Armor Effects Config
#Define multipliers for mob detection range and speed when a player wears specific armor items.
#Format: item_id=speedMultiplier,rangeMultiplier
#Example: minecraft:diamond_helmet=0.5,0.5
[armor_effects]
	effects = ["minecraft:diamond_helmet=0.9,0.6", "minecraft:diamond_chestplate=1.0,0.7"]

#Death Angels Mod Config
#Defines the threshold detection (how hard the player must speak)
#You need this mod for this parameter: https://www.curseforge.com/minecraft/mc-mods/death-angels
[death_angels_config]
	#Range: -127.0 ~ 0.0
	death_angels_threshold = -20.0

#OverMan's Quiet place Mod Config
#Defines the threshold detection (how hard the player must speak)
#You need this mod for this parameter: https://www.curseforge.com/minecraft/mc-mods/overmans-quiet-place
[quiet_place_overman_config]
	#Range: -127.0 ~ 0.0
	quiet_place_overman_threshold = -30.0

#Debugging Config
[debugging]
	debug = false

